language: go
sudo: false
matrix:
  include:
    - go: 1.x
      env: LATEST=true
    - go: 1.9
    - go: 1.8

install:
  - bin/setup

script:
  - diff -u <(echo -n) <(gofmt -d .)
  - bin/test
  - if [ "${LATEST}" == "true" ]; then OSSES="linux darwin windows" bin/build; else bin/build; fi

deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: $TOKEN
  file:
  - shiori_windows_amd64.exe
  - shiori_darwin_amd64
  - shiori_linux_amd64
  on:
    tags: true
    branches:
      only:
        - master
    condition: $LATEST = true
